Реализация функции сортировки строк
js-tasks-ru/js-20200928_alexeymoiseev pull request #2
Opened 2020-10-04 16:30 UTC by ggeeenn

2020-10-04 16:36 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-05 07:20 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-06 14:15 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortArr = arr.slice();
`sortArr` - это `const`

2020-10-06 14:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return a.localeCompare(b, ["ru", "en"], {caseFirst: 'upper'})
строка 12 дублирует строку 14 за исключением порядка аргментов в `localCompare`, необходимо избавиться от дубликатов

2020-10-06 14:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (fields.includes(prop[0], 0)) resObj[prop[0]] = prop[1];
нет необходимости передавать второй аргумент в `includes`, тем более в Вашем решении он всегда 0

2020-10-06 14:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let resObj = {};
это `const`

2020-10-06 14:18 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let resObj = {};
замечания аналогичны `pick`

2020-10-06 14:18 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-06 17:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:41 UTC, dosandk approved these changes
good 👍

2020-10-07 18:42 UTC, merged